# A representation of the Magic Item Tables given in the
# 5th edition Dungeon Master's Guide.
#
# Rolling process: randomly choose element of 'magic_*' list
#                  randonly choose element of list just chosen
#                  return newest choice as result of the 'roll'
#
# Feel free to change the lists but make sure any new items
# are recorded in magicmappings.py.

tables = {
    "magic_com": [
        [
            "Armor of Gleaming (Hide)",
            "Armor of Gleaming (Chain Shirt)",
            "Armor of Gleaming (Scale Mail)",
            "Armor of Gleaming (Breastplate)",
            "Armor of Gleaming (Half Plate)",
            ],
        [
            "Armor of Gleaming (Ring Mail)",
            "Armor of Gleaming (Chain Mail)",
            "Armor of Gleaming (Splint)",
            "Armor of Gleaming (Plate)",
            ],
        ["Bead of Nourishment"],
        ["Bead of Refreshment"],
        ["Boots of False Tracks"],
        ["Candle of the Deep"],
        [
            "Cast-Off Armor (Padded)",
            "Cast-Off Armor (Leather)",
            "Cast-Off Armor (Studded Leather)",
            ],
        [
            "Cast-Off Armor (Hide)",
            "Cast-Off Armor (Chain Shirt)",
            "Cast-Off Armor (Scale Mail)",
            "Cast-Off Armor (Breastplate)",
            "Cast-Off Armor (Half Plate)",
            ],
        [
            "Cast-Off Armor (Ring Mail)",
            "Cast-Off Armor (Chain Mail)",
            "Cast-Off Armor (Splint)",
            "Cast-Off Armor (Plate)",
            ],
        ["Charlatan's Die"],
        ["Chest of Preserving"],
        ["Cloak of Billowing"],
        ["Cloak of Many Fashions"],
        ["Clockwork Amulet"],
        ["Clothes of Mending"],
        ["Dark Shard Amulet"],
        ["Dread Helm"],
        ["Ear Horn of Listening"],
        ["Enduring Spellbook"],
        ["Ersatz Eye"],
        ["Hat of Vermin"],
        ["Hat of Wizardry"],
        ["Heward's Handy Spice Pouch"],
        ["Horn of Silent Alarm"],
        ["Instrument of Illusions"],
        ["Instrument of Scribing"],
        ["Lock of Trickery"],
        [
            "Moon-Touched Sword (Greatsword)",
            "Moon-Touched Sword (Longsword)",
            "Moon-Touched Sword (Rapier)",
            "Moon-Touched Sword (Scimitar)",
            "Moon-Touched Sword (Shortsword)",
            ],
        ["Mystery Key"],
        ["Orb of Direction"],
        ["Orb of Gonging"],
        ["Orb of Time"],
        ["Perfume of Bewitching"],
        ["Pipe of Remembrance"],
        ["Pipe of Smoke Monsters"],
        ["Pole of Angling"],
        ["Pole of Collapsing"],
        ["Pot of Awakening"],
        ["Potion of Climbing"],
        ["Potion of Comprehension"],
        ["Potion of Healing"],
        ["Potion of Watchful Rest"],
        ["Pressure Capsule"],
        ["Rope of Mending"],
        ["Ruby of the War Mage"],
        ["Shield of Expression"],
        [
            "Smoldering Armor (Padded)",
            "Smoldering Armor (Leather)",
            "Smoldering Armor (Studded Leather)",
            ],
        [
            "Smoldering Armor (Hide)",
            "Smoldering Armor (Chain Shirt)",
            "Smoldering Armor (Scale Mail)",
            "Smoldering Armor (Breastplate)",
            "Smoldering Armor (Half Plate)",
            ],
        [
            "Smoldering Armor (Ring Mail)",
            "Smoldering Armor (Chain Mail)",
            "Smoldering Armor (Splint)",
            "Smoldering Armor (Plate)",
            ],
        ["Spell Scroll (Cantrip)"],
        ["Spell Scroll (1st Level)"],
        ["Staff of Adornment"],
        ["Staff of Birdcalls"],
        ["Staff of Flowers"],
        ["Talking Doll"],
        ["Tankard of Plenty"],
        ["Tankard of Sobriety"],
        ["Unbreakable Arrow, 5"],
        ["Veteran's Cane"],
        [
            "Walloping Ammunition (Arrow), 5",
            "Walloping Ammunition (Blowgun Needle), 5",
            "Walloping Ammunition (Crossbow Bolt), 5",
            "Walloping Ammunition (Sling Bullet), 5",
            ],
        ["Wand of Conducting"],
        ["Wand of Pyrotechnics"],
        ["Wand of Scowls"],
        ["Wand of Smiles"],
    ],
    "magic_a": [
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Potion of Healing"],
        ["Spell Scroll (Cantrip)"],
        ["Spell Scroll (Cantrip)"],
        ["Spell Scroll (Cantrip)"],
        ["Spell Scroll (Cantrip)"],
        ["Spell Scroll (Cantrip)"],
        ["Spell Scroll (Cantrip)"],
        ["Spell Scroll (Cantrip)"],
        ["Spell Scroll (Cantrip)"],
        ["Spell Scroll (Cantrip)"],
        ["Spell Scroll (Cantrip)"],
        ["Potion of Climbing"],
        ["Potion of Climbing"],
        ["Potion of Climbing"],
        ["Potion of Climbing"],
        ["Potion of Climbing"],
        ["Potion of Climbing"],
        ["Potion of Climbing"],
        ["Potion of Climbing"],
        ["Potion of Climbing"],
        ["Potion of Climbing"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (1st Level)"],
        ["Spell Scroll (2nd Level)"],
        ["Spell Scroll (2nd Level)"],
        ["Spell Scroll (2nd Level)"],
        ["Spell Scroll (2nd Level)"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Bag of Holding"],
        ["Driftglobe"],
    ],
    "magic_b": [
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Greater Healing"],
        ["Potion of Fire Breath"],
        ["Potion of Fire Breath"],
        ["Potion of Fire Breath"],
        ["Potion of Fire Breath"],
        ["Potion of Fire Breath"],
        ["Potion of Fire Breath"],
        ["Potion of Fire Breath"],
        ["Potion of Resistance"],
        ["Potion of Resistance"],
        ["Potion of Resistance"],
        ["Potion of Resistance"],
        ["Potion of Resistance"],
        ["Potion of Resistance"],
        ["Potion of Resistance"],
        ["Ammunition, +1"],
        ["Ammunition, +1"],
        ["Ammunition, +1"],
        ["Ammunition, +1"],
        ["Ammunition, +1"],
        ["Potion of Animal Friendship"],
        ["Potion of Animal Friendship"],
        ["Potion of Animal Friendship"],
        ["Potion of Animal Friendship"],
        ["Potion of Animal Friendship"],
        ["Potion of Hill Giant Strength"],
        ["Potion of Hill Giant Strength"],
        ["Potion of Hill Giant Strength"],
        ["Potion of Hill Giant Strength"],
        ["Potion of Hill Giant Strength"],
        ["Potion of Growth"],
        ["Potion of Growth"],
        ["Potion of Growth"],
        ["Potion of Growth"],
        ["Potion of Growth"],
        ["Potion of Water Breathing"],
        ["Potion of Water Breathing"],
        ["Potion of Water Breathing"],
        ["Potion of Water Breathing"],
        ["Potion of Water Breathing"],
        ["Spell Scroll (2nd Level)"],
        ["Spell Scroll (2nd Level)"],
        ["Spell Scroll (2nd Level)"],
        ["Spell Scroll (2nd Level)"],
        ["Spell Scroll (2nd Level)"],
        ["Spell Scroll (3rd Level)"],
        ["Spell Scroll (3rd Level)"],
        ["Spell Scroll (3rd Level)"],
        ["Spell Scroll (3rd Level)"],
        ["Spell Scroll (3rd Level)"],
        ["Bag of Holding"],
        ["Bag of Holding"],
        ["Bag of Holding"],
        ["Keoghtom's Ointment"],
        ["Keoghtom's Ointment"],
        ["Keoghtom's Ointment"],
        ["Oil of Slipperiness"],
        ["Oil of Slipperiness"],
        ["Oil of Slipperiness"],
        ["Dust of Disappearance"],
        ["Dust of Disappearance"],
        ["Dust of Dryness"],
        ["Dust of Dryness"],
        ["Dust of Sneezing and Choking"],
        ["Dust of Sneezing and Choking"],
        ["Elemental Gem"],
        ["Elemental Gem"],
        ["Philter of Love"],
        ["Philter of Love"],
        ["Alchemy Jug"],
        ["Cap of Water Breathing"],
        ["Cloak of the Manta Ray"],
        ["Driftglobe"],
        ["Goggles of Night"],
        ["Helm of Comprehending Languages"],
        ["Immovable Rod"],
        ["Lantern of Revealing"],
        [
            "Mariner's Armor (Padded)",
            "Mariner's Armor (Leather)",
            "Mariner's Armor (Studded Leather)",
            "Mariner's Armor (Hide)",
            "Mariner's Armor (Chain Shirt)",
            "Mariner's Armor (Scale Mail)",
            "Mariner's Armor (Breastplate)",
            "Mariner's Armor (Half Plate)",
            "Mariner's Armor (Ring Mail)",
            "Mariner's Armor (Chain Mail)",
            "Mariner's Armor (Splint)",
            "Mariner's Armor (Plate)",
            ],
        [
            "Mithral Armor (Chain Shirt)",
            "Mithral Armor (Scale Mail)",
            "Mithral Armor (Breastplate)",
            "Mithral Armor (Half Plate)",
            "Mithral Armor (Ring Mail)",
            "Mithral Armor (Chain Mail)",
            "Mithral Armor (Splint)",
            "Mithral Armor (Plate)",
            ],
        ["Potion of Poison"],
        ["Ring of Swimming"],
        ["Robe of Useful Items"],
        ["Rope of Climbing"],
        ["Saddle of the Cavalier"],
        ["Wand of Magic Detection"],
        ["Wand of Secrets"],
    ],
    "magic_c": [
        ["Potion of Superior Healing"],
        ["Potion of Superior Healing"],
        ["Potion of Superior Healing"],
        ["Potion of Superior Healing"],
        ["Potion of Superior Healing"],
        ["Potion of Superior Healing"],
        ["Potion of Superior Healing"],
        ["Potion of Superior Healing"],
        ["Potion of Superior Healing"],
        ["Potion of Superior Healing"],
        ["Potion of Superior Healing"],
        ["Potion of Superior Healing"],
        ["Potion of Superior Healing"],
        ["Potion of Superior Healing"],
        ["Potion of Superior Healing"],
        ["Spell Scroll (4th Level)"],
        ["Spell Scroll (4th Level)"],
        ["Spell Scroll (4th Level)"],
        ["Spell Scroll (4th Level)"],
        ["Spell Scroll (4th Level)"],
        ["Spell Scroll (4th Level)"],
        ["Spell Scroll (4th Level)"],
        ["Ammunition, +2"],
        ["Ammunition, +2"],
        ["Ammunition, +2"],
        ["Ammunition, +2"],
        ["Ammunition, +2"],
        ["Potion of Clairvoyance"],
        ["Potion of Clairvoyance"],
        ["Potion of Clairvoyance"],
        ["Potion of Clairvoyance"],
        ["Potion of Clairvoyance"],
        ["Potion of Diminution"],
        ["Potion of Diminution"],
        ["Potion of Diminution"],
        ["Potion of Diminution"],
        ["Potion of Diminution"],
        ["Potion of Gaseous Form"],
        ["Potion of Gaseous Form"],
        ["Potion of Gaseous Form"],
        ["Potion of Gaseous Form"],
        ["Potion of Gaseous Form"],
        ["Potion of Frost Giant Strength"],
        ["Potion of Frost Giant Strength"],
        ["Potion of Frost Giant Strength"],
        ["Potion of Frost Giant Strength"],
        ["Potion of Frost Giant Strength"],
        ["Potion of Stone Giant Strength"],
        ["Potion of Stone Giant Strength"],
        ["Potion of Stone Giant Strength"],
        ["Potion of Stone Giant Strength"],
        ["Potion of Stone Giant Strength"],
        ["Potion of Heroism"],
        ["Potion of Heroism"],
        ["Potion of Heroism"],
        ["Potion of Heroism"],
        ["Potion of Heroism"],
        ["Potion of Invulnerability"],
        ["Potion of Invulnerability"],
        ["Potion of Invulnerability"],
        ["Potion of Invulnerability"],
        ["Potion of Invulnerability"],
        ["Potion of Mind Reading"],
        ["Potion of Mind Reading"],
        ["Potion of Mind Reading"],
        ["Potion of Mind Reading"],
        ["Potion of Mind Reading"],
        ["Spell Scroll (5th Level)"],
        ["Spell Scroll (5th Level)"],
        ["Spell Scroll (5th Level)"],
        ["Spell Scroll (5th Level)"],
        ["Spell Scroll (5th Level)"],
        ["Elixir of Health"],
        ["Elixir of Health"],
        ["Elixir of Health"],
        ["Oil of Etherealness"],
        ["Oil of Etherealness"],
        ["Oil of Etherealness"],
        ["Potion of Fire Giant Strength"],
        ["Potion of Fire Giant Strength"],
        ["Potion of Fire Giant Strength"],
        ["Quaal's Feather Token"],
        ["Quaal's Feather Token"],
        ["Quaal's Feather Token"],
        ["Scroll of Protection"],
        ["Scroll of Protection"],
        ["Scroll of Protection"],
        ["Bag of Beans"],
        ["Bag of Beans"],
        ["Bead of Force"],
        ["Bead of Force"],
        ["Chime of Opening"],
        ["Decanter of Endless Water"],
        ["Eyes of Minute Seeing"],
        ["Folding Boat"],
        ["Heward's Handy Haversack"],
        ["Horseshoes of Speed"],
        ["Necklace of Fireballs"],
        ["Periapt of Health"],
        ["Sending Stones"],
    ],
    "magic_d": [
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Invisibility"],
        ["Potion of Invisibility"],
        ["Potion of Invisibility"],
        ["Potion of Invisibility"],
        ["Potion of Invisibility"],
        ["Potion of Invisibility"],
        ["Potion of Invisibility"],
        ["Potion of Invisibility"],
        ["Potion of Invisibility"],
        ["Potion of Invisibility"],
        ["Potion of Speed"],
        ["Potion of Speed"],
        ["Potion of Speed"],
        ["Potion of Speed"],
        ["Potion of Speed"],
        ["Potion of Speed"],
        ["Potion of Speed"],
        ["Potion of Speed"],
        ["Potion of Speed"],
        ["Potion of Speed"],
        ["Spell Scroll (6th Level)"],
        ["Spell Scroll (6th Level)"],
        ["Spell Scroll (6th Level)"],
        ["Spell Scroll (6th Level)"],
        ["Spell Scroll (6th Level)"],
        ["Spell Scroll (6th Level)"],
        ["Spell Scroll (6th Level)"],
        ["Spell Scroll (6th Level)"],
        ["Spell Scroll (6th Level)"],
        ["Spell Scroll (6th Level)"],
        ["Spell Scroll (7th Level)"],
        ["Spell Scroll (7th Level)"],
        ["Spell Scroll (7th Level)"],
        ["Spell Scroll (7th Level)"],
        ["Spell Scroll (7th Level)"],
        ["Spell Scroll (7th Level)"],
        ["Spell Scroll (7th Level)"],
        ["Ammunition, +3"],
        ["Ammunition, +3"],
        ["Ammunition, +3"],
        ["Ammunition, +3"],
        ["Ammunition, +3"],
        ["Oil of Sharpness"],
        ["Oil of Sharpness"],
        ["Oil of Sharpness"],
        ["Oil of Sharpness"],
        ["Oil of Sharpness"],
        ["Potion of Flying"],
        ["Potion of Flying"],
        ["Potion of Flying"],
        ["Potion of Flying"],
        ["Potion of Flying"],
        ["Potion of Cloud Giant Strength"],
        ["Potion of Cloud Giant Strength"],
        ["Potion of Cloud Giant Strength"],
        ["Potion of Cloud Giant Strength"],
        ["Potion of Cloud Giant Strength"],
        ["Potion of Longevity"],
        ["Potion of Longevity"],
        ["Potion of Longevity"],
        ["Potion of Longevity"],
        ["Potion of Longevity"],
        ["Potion of Vitality"],
        ["Potion of Vitality"],
        ["Potion of Vitality"],
        ["Potion of Vitality"],
        ["Potion of Vitality"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Horseshoes of A Zephyr"],
        ["Horseshoes of A Zephyr"],
        ["Horseshoes of A Zephyr"],
        ["Nolzur's Marvelous Pigments"],
        ["Nolzur's Marvelous Pigments"],
        ["Nolzur's Marvelous Pigments"],
        ["Bag of Devouring"],
        ["Portable Hole"],
    ],
    "magic_e": [
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Spell Scroll (8th Level)"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Storm Giant Strength"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Potion of Supreme Healing"],
        ["Spell Scroll (9th Level)"],
        ["Spell Scroll (9th Level)"],
        ["Spell Scroll (9th Level)"],
        ["Spell Scroll (9th Level)"],
        ["Spell Scroll (9th Level)"],
        ["Spell Scroll (9th Level)"],
        ["Spell Scroll (9th Level)"],
        ["Spell Scroll (9th Level)"],
        ["Spell Scroll (9th Level)"],
        ["Spell Scroll (9th Level)"],
        ["Spell Scroll (9th Level)"],
        ["Spell Scroll (9th Level)"],
        ["Spell Scroll (9th Level)"],
        ["Spell Scroll (9th Level)"],
        ["Spell Scroll (9th Level)"],
        ["Universal Solvent"],
        ["Universal Solvent"],
        ["Universal Solvent"],
        ["Universal Solvent"],
        ["Universal Solvent"],
        ["Universal Solvent"],
        ["Universal Solvent"],
        ["Universal Solvent"],
        ["Arrow of Slaying"],
        ["Arrow of Slaying"],
        ["Arrow of Slaying"],
        ["Arrow of Slaying"],
        ["Arrow of Slaying"],
        ["Sovereign Glue"],
        ["Sovereign Glue"],
    ],
    "magic_f": [
        ["Weapon, +1"],
        ["Weapon, +1"],
        ["Weapon, +1"],
        ["Weapon, +1"],
        ["Weapon, +1"],
        ["Weapon, +1"],
        ["Weapon, +1"],
        ["Weapon, +1"],
        ["Weapon, +1"],
        ["Weapon, +1"],
        ["Weapon, +1"],
        ["Weapon, +1"],
        ["Weapon, +1"],
        ["Weapon, +1"],
        ["Weapon, +1"],
        ["Shield, +1"],
        ["Shield, +1"],
        ["Shield, +1"],
        ["Sentinel Shield"],
        ["Sentinel Shield"],
        ["Sentinel Shield"],
        ["Amulet of Proof against Detection and Location"],
        ["Amulet of Proof against Detection and Location"],
        ["Boots of Elvenkind"],
        ["Boots of Elvenkind"],
        ["Boots of Striding and Springing"],
        ["Boots of Striding and Springing"],
        ["Bracers of Archery"],
        ["Bracers of Archery"],
        ["Brooch of Shielding"],
        ["Brooch of Shielding"],
        ["Broom of Flying"],
        ["Broom of Flying"],
        ["Cloak of Elvenkind"],
        ["Cloak of Elvenkind"],
        ["Cloak of Protection"],
        ["Cloak of Protection"],
        ["Gauntlets of Ogre Power"],
        ["Gauntlets of Ogre Power"],
        ["Hat of Disguise"],
        ["Hat of Disguise"],
        ["Javelin of Lightning"],
        ["Javelin of Lightning"],
        ["Pearl of Power"],
        ["Pearl of Power"],
        ["Rod of the Pact Keeper, +1"],
        ["Rod of the Pact Keeper, +1"],
        ["Slippers of Spider Climbing"],
        ["Slippers of Spider Climbing"],
        ["Staff of the Adder"],
        ["Staff of the Adder"],
        ["Staff of the Python"],
        ["Staff of the Python"],
        ["Sword of Vengeance"],
        ["Sword of Vengeance"],
        ["Trident of Fish Command"],
        ["Trident of Fish Command"],
        ["Wand of Magic Missiles"],
        ["Wand of Magic Missiles"],
        ["Wand of the War Mage, +1"],
        ["Wand of the War Mage, +1"],
        ["Wand of Web"],
        ["Wand of Web"],
        ["Weapon of Warning"],
        ["Weapon of Warning"],
        ["Adamantine Armor (Chain Mail)"],
        ["Adamantine Armor (Chain Shirt)"],
        ["Adamantine Armor (Ring Mail)"],
        ["Adamantine Armor (Scale Mail)"],
        ["Bag of Tricks (Gray)"],
        ["Bag of Tricks (Rust)"],
        ["Bag of Tricks (Tan)"],
        ["Boots of the Winterlands"],
        ["Circlet of Blasting"],
        ["Deck of Illusions"],
        ["Eversmoking Bottle"],
        ["Eyes of Charming"],
        ["Eyes of the Eagle"],
        ["Figurine of Wondrous Power (Silver Raven)"],
        ["Gem of Brightness"],
        ["Gloves of Missile Snaring"],
        ["Gloves of Swimming and Climbing"],
        ["Gloves of Thievery"],
        ["Headband of Intellect"],
        ["Helm of Telepathy"],
        ["Instrument of the Bards (Doss Lute)"],
        ["Instrument of the Bards (Fochlucan Bandore)"],
        ["Instrument of the Bards (Mac-Fuimidh Cittern)"],
        ["Medallion of Thoughts"],
        ["Necklace of Adaptation"],
        ["Periapt of Wound Closure"],
        ["Pipes of Haunting"],
        ["Pipes of the Sewers"],
        ["Ring of Jumping"],
        ["Ring of Mind Shielding"],
        ["Ring of Warmth"],
        ["Ring of Water Walking"],
        ["Quiver of Ehlonna"],
        ["Stone of Good Luck"],
        ["Wind Fan"],
        ["Winged Boots"],
    ],
    "magic_g": [
        ["Weapon, +2"],
        ["Weapon, +2"],
        ["Weapon, +2"],
        ["Weapon, +2"],
        ["Weapon, +2"],
        ["Weapon, +2"],
        ["Weapon, +2"],
        ["Weapon, +2"],
        ["Weapon, +2"],
        ["Weapon, +2"],
        ["Weapon, +2"],
        [
            "Figurine of Wondrous Power (Bronze Griffon)", 
            "Figurine of Wondrous Power (Ebony Fly)", 
            "Figurine of Wondrous Power (Golden Lions)", 
            "Figurine of Wondrous Power (Ivory Goats)", 
            "Figurine of Wondrous Power (Marble Elephant)", 
            "Figurine of Wondrous Power (Onyx Dog)", 
            "Figurine of Wondrous Power (Onyx Dog)", 
            "Figurine of Wondrous Power (Serpentine Owl)",
            ],
        [
            "Figurine of Wondrous Power (Bronze Griffon)", 
            "Figurine of Wondrous Power (Ebony Fly)", 
            "Figurine of Wondrous Power (Golden Lions)", 
            "Figurine of Wondrous Power (Ivory Goats)", 
            "Figurine of Wondrous Power (Marble Elephant)", 
            "Figurine of Wondrous Power (Onyx Dog)", 
            "Figurine of Wondrous Power (Onyx Dog)", 
            "Figurine of Wondrous Power (Serpentine Owl)",
            ],
        [
            "Figurine of Wondrous Power (Bronze Griffon)", 
            "Figurine of Wondrous Power (Ebony Fly)", 
            "Figurine of Wondrous Power (Golden Lions)", 
            "Figurine of Wondrous Power (Ivory Goats)", 
            "Figurine of Wondrous Power (Marble Elephant)", 
            "Figurine of Wondrous Power (Onyx Dog)", 
            "Figurine of Wondrous Power (Onyx Dog)", 
            "Figurine of Wondrous Power (Serpentine Owl)",
            ],
        ["Adamantine Armor (Breastplate)"],
        ["Adamantine Armor (Splint)"],
        ["Amulet of Health"],
        ["Armor of Vulnerability"],
        ["Arrow-Catching Shield"],
        ["Belt of Dwarvenkind"],
        ["Belt of Hill Giant Strength"],
        ["Berserker Axe"],
        ["Boots of Levitation"],
        ["Boots of Speed"],
        ["Bowl of Commanding Water Elementals"],
        ["Bracers of Defense"],
        ["Brazier of Commanding Fire Elementals"],
        ["Cape of the Mountebank"],
        ["Censer of Controlling Air Elementals"],
        ["Armor, +1 (Chain Mail)"],
        ["Armor of Resistance (Chain Mail)"],
        ["Armor, +1 (Chain Shirt)"],
        ["Armor of Resistance (Chain Shirt)"],
        ["Cloak of Displacement"],
        ["Cloak of the Bat"],
        ["Cube of Force"],
        ["Daern's Instant Fortress"],
        ["Dagger of Venom"],
        ["Dimensional Shackles"],
        ["Dragon Slayer"],
        ["Elven Chain"],
        ["Flame Tongue"],
        ["Gem of Seeing"],
        ["Giant Slayer"],
        ["Glamoured Studded Leather"],
        ["Helm of Teleportation"],
        ["Horn of Blasting"],
        ["Horn of Valhalla (Silver or Brass)"],
        ["Instrument of the Bards (Canaith Mandolin)"],
        ["Instrument of the Bards (Cli Lyre)"],
        ["Ioun Stone (Awareness)"],
        ["Ioun Stone (Protection)"],
        ["Ioun Stone (Reserve)"],
        ["Ioun Stone (Sustenance)"],
        ["Iron Bands of Bilarro"],
        ["Armor, +1 (Leather)"],
        ["Armor, +1 (Padded)"],
        ["Armor of Resistance (Leather)"],
        ["Armor of Resistance (Padded)"],
        ["Mace of Disruption"],
        ["Mace of Smiting"],
        ["Mace of Terror"],
        ["Mantle of Spell Resistance"],
        ["Necklace of Prayer Beads"],
        ["Periapt of Proof against Poison"],
        ["Ring of Animal Influence"],
        ["Ring of Evasion"],
        ["Ring of Feather Falling"],
        ["Ring of Free Action"],
        ["Ring of Protection"],
        ["Ring of Resistance"],
        ["Ring of Spell Storing"],
        ["Ring of the Ram"],
        ["Ring of X-Ray Vision"],
        ["Robe of Eyes"],
        ["Rod of Rulership"],
        ["Rod of the Pact Keeper, +2"],
        ["Rope of Entanglement"],
        ["Armor, +1 (Ring Mail)"],
        ["Armor, +1 (Scale Mail)"],
        ["Armor of Resistance (Ring Mail)"],
        ["Armor of Resistance (Scale Mail)"],
        ["Shield, +2"],
        ["Shield of Missile Attraction"],
        ["Staff of Charming"],
        ["Staff of Healing"],
        ["Staff of Swarming Insects"],
        ["Staff of the Woodlands"],
        ["Staff of Withering"],
        ["Stone of Controlling Earth Elementals"],
        ["Sun Blade"],
        ["Sword of Life Stealing"],
        ["Sword of Wounding"],
        ["Tentacle Rod"],
        ["Vicious Weapon"],
        ["Wand of Binding"],
        ["Wand of Enemy Detection"],
        ["Wand of Fear"],
        ["Wand of Fireballs"],
        ["Wand of Lightning Bolts"],
        ["Wand of Paralysis"],
        ["Wand of the War Mage, +2"],
        ["Wand of Wonder"],
        ["Wings of Flying"],
    ],
    "magic_h": [
        ["Weapon, +3"],
        ["Weapon, +3"],
        ["Weapon, +3"],
        ["Weapon, +3"],
        ["Weapon, +3"],
        ["Weapon, +3"],
        ["Weapon, +3"],
        ["Weapon, +3"],
        ["Weapon, +3"],
        ["Weapon, +3"],
        ["Amulet of the Planes"],
        ["Amulet of the Planes"],
        ["Carpet of Flying"],
        ["Carpet of Flying"],
        ["Crystal Ball of Scrying"],
        ["Crystal Ball of Scrying"],
        ["Ring of Regeneration"],
        ["Ring of Regeneration"],
        ["Ring of Shooting Stars"],
        ["Ring of Shooting Stars"],
        ["Ring of Telekinesis"],
        ["Ring of Telekinesis"],
        ["Robe of Scintillating Colors"],
        ["Robe of Scintillating Colors"],
        ["Robe of Stars"],
        ["Robe of Stars"],
        ["Rod of Absorption"],
        ["Rod of Absorption"],
        ["Rod of Alertness"],
        ["Rod of Alertness"],
        ["Rod of Security"],
        ["Rod of Security"],
        ["Rod of the Pact Keeper, +3"],
        ["Rod of the Pact Keeper, +3"],
        ["Scimitar of Speed"],
        ["Scimitar of Speed"],
        ["Shield, +3"],
        ["Shield, +3"],
        ["Staff of Fire"],
        ["Staff of Fire"],
        ["Staff of Frost"],
        ["Staff of Frost"],
        ["Staff of Power"],
        ["Staff of Power"],
        ["Staff of Striking"],
        ["Staff of Striking"],
        ["Staff of Thunder and Lightning"],
        ["Staff of Thunder and Lightning"],
        ["Sword of Sharpness"],
        ["Sword of Sharpness"],
        ["Wand of Polymorph"],
        ["Wand of Polymorph"],
        ["Wand of the War Mage, +3"],
        ["Wand of the War Mage, +3"],
        ["Adamantine Armor (Half Plate)"],
        ["Adamantine Armor (Plate)"],
        ["Animated Shield"],
        ["Belt of Fire Giant Strength"],
        ["Belt of Frost (or Stone) Giant Strength"],
        ["Armor, +1 (Breastplate)"],
        ["Armor of Resistance (Breastplate)"],
        ["Candle of Invocation"],
        ["Armor, +2 (Chain Mail)"],
        ["Armor, +2 (Chain Shirt)"],
        ["Cloak of Arachnida"],
        ["Dancing Sword"],
        ["Demon Armor"],
        ["Dragon Scale Mail"],
        ["Dwarven Plate"],
        ["Dwarven Thrower"],
        ["Efreeti Bottle"],
        ["Figurine of Wondrous Power (Obsidian Steed)"],
        ["Frost Brand"],
        ["Helm of Brilliance"],
        ["Horn of Valhalla (Bronze)"],
        ["Instrument of the Bards (Anstruth Harp)"],
        ["Ioun Stone (Absorption)"],
        ["Ioun Stone (Agility)"],
        ["Ioun Stone (Fortitude)"],
        ["Ioun Stone (Insight)"],
        ["Ioun Stone (Intellect)"],
        ["Ioun Stone (Leadership)"],
        ["Ioun Stone (Strength)"],
        ["Armor, +2 (Leather)"],
        ["Armor, +2 (Padded)"],
        ["Manual of Bodily Health"],
        ["Manual of Gainful Exercise"],
        ["Manual of Golems"],
        ["Manual of Quickness of Action"],
        ["Mirror of Life Trapping"],
        ["Nine Lives Stealer"],
        ["Oath Bow"],
        ["Armor, +2 (Ring Mail)"],
        ["Armor, +2 (Scale Mail)"],
        ["Spellguard Shield"],
        ["Armor, +1 (Splint)"],
        ["Armor of Resistance (Splint)"],
        ["Armor, +1 (Hide)"],
        ["Armor, +1 (Studded Leather)"],
        ["Armor of Resistance (Hide)"],
        ["Armor of Resistance (Studded Leather)"],
        ["Tome of Clear Thought"],
        ["Tome of Leadership and Influence"],
        ["Tome of Understanding"],
    ],
    "magic_i": [
        ["Defender"],
        ["Defender"],
        ["Defender"],
        ["Defender"],
        ["Defender"],
        ["Hammer of Thunderbolts"],
        ["Hammer of Thunderbolts"],
        ["Hammer of Thunderbolts"],
        ["Hammer of Thunderbolts"],
        ["Hammer of Thunderbolts"],
        ["Luck Blade"],
        ["Luck Blade"],
        ["Luck Blade"],
        ["Luck Blade"],
        ["Luck Blade"],
        ["Sword of Answering"],
        ["Sword of Answering"],
        ["Sword of Answering"],
        ["Sword of Answering"],
        ["Sword of Answering"],
        ["Holy Avenger"],
        ["Holy Avenger"],
        ["Holy Avenger"],
        ["Ring of Djinni Summoning"],
        ["Ring of Djinni Summoning"],
        ["Ring of Djinni Summoning"],
        ["Ring of Invisibility"],
        ["Ring of Invisibility"],
        ["Ring of Invisibility"],
        ["Ring of Spell Turning"],
        ["Ring of Spell Turning"],
        ["Ring of Spell Turning"],
        ["Rod of Lordly Might"],
        ["Rod of Lordly Might"],
        ["Rod of Lordly Might"],
        ["Staff of the Magi"],
        ["Staff of the Magi"],
        ["Staff of the Magi"],
        ["Vorpal Sword"],
        ["Vorpal Sword"],
        ["Vorpal Sword"],
        ["Belt of Cloud Giant Strength"],
        ["Belt of Cloud Giant Strength"],
        ["Armor, +2 (Breastplate)"],
        ["Armor, +2 (Breastplate)"],
        ["Armor, +3 (Chain Mail)"],
        ["Armor, +3 (Chain Mail)"],
        ["Armor, +3 (Chain Shirt)"],
        ["Armor, +3 (Chain Shirt)"],
        ["Cloak of Invisibility"],
        ["Cloak of Invisibility"],
        [
            "Crystal Ball of Mind Reading", 
            "Crystal Ball of Telepathy", 
            "Crystal Ball of True Seeing",
            ],
        [
            "Crystal Ball of Mind Reading", 
            "Crystal Ball of Telepathy", 
            "Crystal Ball of True Seeing",
            ],
        ["Armor, +1 (Half Plate)"],
        ["Armor, +1 (Half Plate)"],
        ["Iron Flask"],
        ["Iron Flask"],
        ["Armor, +3 (Leather)"],
        ["Armor, +3 (Leather)"],
        ["Armor, +3 (Padded)"],
        ["Armor, +3 (Padded)"],
        ["Armor, +1 (Plate)"],
        ["Armor, +1 (Plate)"],
        ["Robe of the Archmagi"],
        ["Robe of the Archmagi"],
        ["Rod of Resurrection"],
        ["Rod of Resurrection"],
        ["Armor, +3 (Ring Mail)"],
        ["Armor, +3 (Ring Mail)"],
        ["Armor, +3 (Scale Mail)"],
        ["Armor, +3 (Scale Mail)"],
        ["Scarab of Protection"],
        ["Scarab of Protection"],
        ["Armor, +2 (Splint)"],
        ["Armor, +2 (Splint)"],
        ["Armor, +2 (Hide)"],
        ["Armor, +2 (Hide)"],
        ["Armor, +2 (Studded Leather)"],
        ["Armor, +2 (Studded Leather)"],
        ["Well of Many Worlds"],
        ["Well of Many Worlds"],
        [
            "Armor, +2 (Half Plate)",
            "Armor, +2 (Half Plate)",
            "Armor, +2 (Plate)",
            "Armor, +2 (Plate)",
            "Armor, +3 (Hide)",
            "Armor, +3 (Hide)",
            "Armor, +3 (Studded Leather)",
            "Armor, +3 (Studded Leather)",
        ],
        [
            "Armor, +3 (Breastplate)",
            "Armor, +3 (Breastplate)",
            "Armor, +3 (Splint)",
            "Armor, +3 (Splint)",
            "Armor, +3 (Half Plate)",
            "Armor, +3 (Plate)",
            ],
        ["Apparatus of Kwalish"],
        ["Armor of Invulnerability"],
        ["Belt of Storm Giant Strength"],
        ["Cubic Gate"],
        ["Deck of Many Things"],
        ["Efreeti Chain"],
        ["Armor of Resistance (Half Plate)"],
        ["Horn of Valhalla (Iron)"],
        ["Instrument of the Bards (Ollamh Harp)"],
        ["Ioun Stone (Greater Absorption)"],
        ["Ioun Stone (Mastery)"],
        ["Ioun Stone (Regeneration)"],
        ["Plate Armor of Etherealness"],
        ["Armor of Resistance (Plate)"],
        ["Ring of Air Elemental Command"],
        ["Ring of Earth Elemental Command"],
        ["Ring of Fire Elemental Command"],
        ["Ring of Three Wishes"],
        ["Ring of Water Elemental Command"],
        ["Sphere of Annihilation"],
        ["Talisman of Pure Good"],
        ["Talisman of the Sphere"],
        ["Talisman of Ultimate Evil"],
        ["Tome of the Stilled Tongue"],
    ]
}
